"""initial-db

Revision ID: b6dc10e7a121
Revises: 
Create Date: 2023-05-15 16:26:57.986544

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import ENUM, JSON

# revision identifiers, used by Alembic.
revision = 'b6dc10e7a121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_audit',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('application_status', sa.String(length=100), nullable=False),
    sa.Column('form_url', sa.String(length=500), nullable=False),
    sa.Column('submitted_by', sa.String(length=300), nullable=True),
    sa.Column('form_id', sa.String(length=100), nullable=False),
    sa.Column('submission_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorization',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='Authorization ID'),
    sa.Column('tenant', sa.String(length=100), nullable=True, comment='Tenant key'),
    sa.Column('auth_type', ENUM('DASHBOARD', 'FORM', 'FILTER', name='authtype'), nullable=False, comment='Auth Type'),
    sa.Column('resource_id', sa.String(length=100), nullable=False, comment='Resource identifier'),
    sa.Column('resource_details', JSON(), nullable=True, comment='Resource details'),
    sa.Column('roles', JSON(sa.String(length=100)), nullable=True, comment='Applicable roles'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='Applicable user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorization_auth_type'), 'authorization', ['auth_type'], unique=False)
    op.create_index(op.f('ix_authorization_resource_id'), 'authorization', ['resource_id'], unique=False)
    op.create_table('filter',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('criteria', JSON(), nullable=True),
    sa.Column('variables', JSON(JSON()), nullable=True),
    sa.Column('properties', JSON(), nullable=True),
    sa.Column('roles', JSON(sa.String(length=100)), nullable=True, comment='Applicable roles'),
    sa.Column('users', JSON(sa.String(length=100)), nullable=True, comment='Applicable users'),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_tenant'), 'filter', ['tenant'], unique=False)
    op.create_table('form_history',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=100), nullable=False),
    sa.Column('parent_form_id', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('change_log', JSON(), nullable=False),
    sa.Column('workflow', sa.Boolean(), nullable=True),
    sa.Column('title', sa.Boolean(), nullable=True),
    sa.Column('component_change', sa.Boolean(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('form_type', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_history_form_id'), 'form_history', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_history_parent_form_id'), 'form_history', ['parent_form_id'], unique=False)
    op.create_table('form_process_mapper',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.String(length=50), nullable=False),
    sa.Column('form_name', sa.String(length=100), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('parent_form_id', sa.String(length=50), nullable=False),
    sa.Column('process_key', sa.String(length=50), nullable=True),
    sa.Column('process_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('comments', sa.String(length=300), nullable=True),
    sa.Column('tenant', sa.String(length=100), nullable=True),
    sa.Column('process_tenant', sa.String(length=100), nullable=True, comment='Tenant ID Mapped to process definition. This will be null for shared process definition.'),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('task_variable', JSON(sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'version', 'tenant', name='_form_version_uc')
    )
    op.create_table('application',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_status', sa.String(length=100), nullable=False),
    sa.Column('form_process_mapper_id', sa.Integer(), nullable=False),
    sa.Column('process_instance_id', sa.String(length=100), nullable=True),
    sa.Column('submission_id', sa.String(length=100), nullable=True),
    sa.Column('latest_form_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['form_process_mapper_id'], ['form_process_mapper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_id', sa.String(length=50), nullable=False),
    sa.Column('data', JSON(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft')
    op.drop_table('application')
    op.drop_table('form_process_mapper')
    op.drop_index(op.f('ix_form_history_parent_form_id'), table_name='form_history')
    op.drop_index(op.f('ix_form_history_form_id'), table_name='form_history')
    op.drop_table('form_history')
    op.drop_index(op.f('ix_filter_tenant'), table_name='filter')
    op.drop_table('filter')
    op.drop_index(op.f('ix_authorization_resource_id'), table_name='authorization')
    op.drop_index(op.f('ix_authorization_auth_type'), table_name='authorization')
    op.drop_table('authorization')
    op.drop_table('application_audit')
    # ### end Alembic commands ###
